# Install: dep install
# Deploy: dep deploy

# Your target domain
your.domain.tld:

  # Put here your hostname
  # https://dashboard.uberspace.de/dashboard/datasheet
  hostname: HOST.uberspace.de

  # Put here your Uberspace username
  user: USERNAME

  # Put here your ssh repository 
  repository: git@github.com:jonnitto/NeosWorkshop.git
  port: 22
  forwardAgent: false
  multiplexing: true
  sshOptions:
    UserKnownHostsFile: /dev/null
    StrictHostKeyChecking: no

  # If you remove this line, you will be asked if you want to install 
  # synchronized bash script from https://github.com/jonnitto/bash
  bash_sync: false
