Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Jonnitto.Slider:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Jonnitto.Slider: true

Carbon:
  IncludeAssets:
    Packages:
      Slider:
        Package: 'Jonnitto.Slider'
        ConditionPrototype: 'Jonnitto.Slider:IncludeCase'
        General:
          Head:
            - Main.css
            - Main.js[defer]
        Backend:
          Head:
            - Backend.css
            - Backend.js[defer]
